import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Provider from "@/components/Provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
